import type { EcaKural } from './tipler';

// ECA kuralları: OLAY (ne olunca) → KOŞUL (hangi durumda) → EYLEM (ne yapılır).
// {id} yer tutucuları kontrol değerleriyle doldurulur. "onler": önlediği sorun kimlikleri.
// Faz: 0 iskelet · 1 TDD sözleşmesi · 2 kalibrasyon · 3 ölçek (kullanıcının yol haritası).
export const KURALLAR: EcaKural[] = [
  // ---------------- Plane: talep ve görev çerçevesi ----------------
  {
    id: 'R01', asama: 'GIR', faz: 0, baslik: 'DoR kapısı',
    olay: 'Görev tetiklendi',
    kosul: 'Görev çerçevesinde zorunlu alan eksik: {alanlar}',
    eylem: 'WAITING_FOR_PO; eksikler Plane\'e yazılır, geliştirme başlamaz',
    kontroller: [{ tur: 'kutu', id: 'alanlar', etiket: 'Zorunlu alanlar', varsayilan: ['problem', 'hikaye', 'ac', 'negatif', 'risk', 'yapma'], secenekler: [
      { deger: 'problem', etiket: 'Problem tanımı' }, { deger: 'hikaye', etiket: 'Kullanıcı hikâyesi' },
      { deger: 'ac', etiket: 'Kabul ölçütleri (Verilen/Olduğunda/O zaman + somut değer)' }, { deger: 'negatif', etiket: 'En az bir olumsuz örnek' },
      { deger: 'risk', etiket: 'Risk sınıfı' }, { deger: 'yapma', etiket: '"Neyi yapma" listesi' }] }],
    onler: ['KP-04', 'AK-06', 'B2-S01'], kaynak: ['Pano A0 (görev çerçevesi)', 'AK-06', 'C5'],
    neden: 'Kabul ölçütü eksikse ajan yeşil test üretir ama iş yanlış olur.',
  },
  {
    id: 'R02', asama: 'GIR', faz: 1, baslik: 'Sınıflandırma güven eşiği',
    olay: 'Tipli karar ajanı (DoR, yönlendirici, olgunluk, risk ön sınıfı) karar verdi',
    kosul: 'Güven < %{esik}',
    eylem: 'Karar daha güçlü modele ya da insana gider',
    kontroller: [{ tur: 'sayi', id: 'esik', etiket: 'Güven eşiği', birim: '%', min: 50, max: 99, varsayilan: 80 }],
    onler: ['B2-S14'], kaynak: ['Pano: Jev değerlendirmesi (eşik kuralı)'],
    neden: 'Etiket kümesinde kalan bir cevap doğru cevap demek değildir.',
  },
  // ---------------- Plane: tetik ----------------
  {
    id: 'R03', asama: 'TET', faz: 0, baslik: 'Tekil tetik',
    olay: 'Webhook ya da uzlaştırıcı bir görevi tetikledi',
    kosul: 'Aynı görev ve kabul sürümü için koşu zaten var',
    eylem: 'Yeni koşu açılmaz; mevcut koşunun bağlantısı Plane yorumuna yazılır (koşu kimliği = görev + kabul sürümü)',
    onler: ['D1-04', 'DP-05', 'D2-06'], kaynak: ['Pano A1 (workflow_id tekil)', 'Codex DP-05', 'D1'],
    neden: 'Gecikmiş ya da yinelenen olay ikinci koşu açarsa iş ve maliyet ikiye katlanır.',
  },
  {
    id: 'R04', asama: 'TET', faz: 0, baslik: 'İmza ve aktör denetimi',
    olay: 'Webhook geldi',
    kosul: 'İmza (X-Plane-Signature, ham gövdenin HMAC-SHA256\'sı) geçersiz, aktör yetkisiz ya da proje → depo eşlemesi yok',
    eylem: 'Reddedilir, gerekçe kaydedilir; koşu açılmaz',
    onler: ['DP-06', 'DE-01', 'B2-S05'], kaynak: ['Pano A1', 'Plane CE v1.4.2', 'Codex DP-06'],
    neden: 'Formda proje adının bulunması o depoya yazma yetkisi değildir.',
  },
  {
    id: 'R05', asama: 'TET', faz: 0, baslik: 'Kaçan olay uzlaştırması',
    olay: 'Her {aralik} dakikada zamanlanmış kontrol',
    kosul: 'Plane\'de tetik durumunda olup koşusu olmayan görev var',
    eylem: 'Eksik koşu tekil kimlikle başlatılır; webhook kanalının sağlığı raporlanır',
    kontroller: [{ tur: 'sayi', id: 'aralik', etiket: 'Uzlaştırma aralığı', birim: 'dk', min: 2, max: 60, varsayilan: 10 }],
    onler: ['D1-02', 'D2-D07', 'DE-02', 'AK-23', 'AK-25', 'AK-24'], kaynak: ['Plane CE: 5xx yeniden denenmez, 5 ağ hatasında webhook kapanır', 'E5', 'AK-23'],
    neden: 'Webhook tek başına güvenilir değil; kaçan olay sessizce kaybolur.',
  },
  {
    id: 'R06', asama: 'TET', faz: 0, baslik: 'Katılım işareti',
    olay: 'Bir iş tetik durumuna geçti',
    kosul: 'İş fabrikaya açılmamış (etiket ya da ayrı durum yok) ya da durum, grup adıyla eşleşiyor',
    eylem: 'İş yok sayılır; insanın elle yürüttüğü işe dokunulmaz',
    onler: ['AK-45'], kaynak: ['AK-45', 'E5: pilotta REVIEW ve WAITING_DECISION da "started" grubundaydı'],
    neden: 'Durum grubu tetik olursa inceleme bekleyen işler de ajana gider.',
  },
  {
    id: 'R07', asama: 'TET', faz: 1, baslik: 'Görev nesli',
    olay: 'İnsan kabul ölçütünü ya da kapsamı değiştirdi',
    kosul: 'Görevin koşusu sürüyor',
    eylem: 'Yeni nesil açılır; eski kanıt yeni nesle taşınmaz, eski neslin yeni dış etkisi engellenir',
    onler: ['DP-05', 'DK-06', 'AK-44'], kaynak: ['Codex ACCEPTANCE', 'E4 (nesil ve girdi özeti)'],
    neden: 'Değişen girdiyle eski kanıt birleşirse "geçti" yanlış işe ait olur.',
  },
  // ---------------- agentic-rdd-development ----------------
  {
    id: 'R08', asama: 'ARS', faz: 0, baslik: 'Netleştirme döngü sınırı',
    olay: 'Araştırma sonrası belirsizlik kaldı',
    kosul: 'Netleştirme döngüsü ≥ {dongu}',
    eylem: 'Soru Plane\'e yazılır, WAITING_FOR_PO; cevapla aynı adımdan devam edilir',
    kontroller: [{ tur: 'sayi', id: 'dongu', etiket: 'En fazla döngü', min: 1, max: 5, varsayilan: 2 }],
    onler: ['KP-13', 'B2-S03'], kaynak: ['policy.yaml: clarification_loops 2', 'Pano A2'],
    neden: 'Ajan belirsizliği kendi başına kapatmaya çalışınca uydurur ya da döner.',
  },
  {
    id: 'R09', asama: 'ARS', faz: 0, baslik: 'Güvenilmeyen içerik talimat değildir',
    olay: 'Ajan issue, PR, README, web sayfası ya da araç çıktısı okuyor',
    kosul: 'İçerik görev tanımının dışından geliyor',
    eylem: 'Veri olarak işaretlenir; aynı oturumda güvenilmeyen içerik + özel veri + dışa yazma bir arada olmaz (Rule of Two)',
    onler: ['B2-S05', 'AK-39', 'D2-05'], kaynak: ['A3', 'B2 S05', 'AK-39'],
    neden: 'Güvenilmeyen metin talimat gibi okunursa sır sızar ya da kod çalışır.',
  },
  {
    id: 'R10', asama: 'ARS', faz: 1, baslik: 'Sürüme özgü doküman ve paket doğrulaması',
    olay: 'Ajan bir kütüphane ya da paket kullanacak',
    kosul: 'Her zaman',
    eylem: 'Resmî, sürüme özgü doküman okunur (Context7); paket adı kayıtta doğrulanır, yerel paket vekilinden kurulur',
    onler: ['B2-S11', 'AK-15'], kaynak: ['B2 S11 (slopsquatting)', 'Pano: web-research + Context7'],
    neden: 'Model eski API önerir ya da var olmayan paket adı uydurur.',
  },
  {
    id: 'R11', asama: 'HAR', faz: 2, baslik: 'Bağımlılık sırası kodla belirlenir',
    olay: 'Görev parçalara bölündü',
    kosul: 'Parçalar arasında bağımlılık var',
    eylem: 'Sıra topolojik sıralamayla belirlenir; bağımsız kümeler paralel başlar; ön koşulu eksik parça başlamaz; en fazla {bolme} yeniden bölme, sonra insan',
    kontroller: [{ tur: 'sayi', id: 'bolme', etiket: 'Yeniden bölme sınırı', min: 1, max: 4, varsayilan: 2 }],
    onler: ['KP-16', 'B2-S09'], kaynak: ['Pano A3', 'Pano: dependency-priority "ajan değil"'],
    neden: 'Kümeleme bir algoritma problemidir; ortak temel eskiyince bütün paketler bayatlar.',
  },
  {
    id: 'R12', asama: 'PLN', faz: 1, baslik: 'Üst kapsam korunur',
    olay: 'Plan parçalara bölündü',
    kosul: 'Üst görevin bir kabul yükümlülüğü hiçbir parçaya bağlanmadı',
    eylem: 'Plan reddedilir; eksik yükümlülük için test, gerekçeli kapsam kararı ya da açık başarısızlık gerekir',
    onler: ['DP-08', 'DK-01'], kaynak: ['Codex DP-08', 'Codex DK-01'],
    neden: 'Yedi parçanın altısı alınınca yedinci yükümlülük sessizce kaybolur.',
  },
  {
    id: 'R13', asama: 'PLN', faz: 1, baslik: 'Farklı aileden plan hakemi',
    olay: 'Plan hazır',
    kosul: 'Risk sınıfı: {esik}',
    eylem: 'Planlayıcıdan farklı model ailesi rubrikle inceler; yüksek riskte insan onayı beklenir (sinyal ile, yoklama değil)',
    kontroller: [{ tur: 'radyo', id: 'esik', etiket: 'Hangi riskte incelensin', varsayilan: 'orta', secenekler: [
      { deger: 'yuksek', etiket: 'Yalnız yüksek' }, { deger: 'orta', etiket: 'Orta ve üstü' }, { deger: 'hepsi', etiket: 'Hepsi' }] }],
    onler: ['B2-S14', 'AK-05', 'AK-46'], kaynak: ['Pano bulguları: plan incelemesini aynı yapay zekâ yapıyor', 'A3: üretici–doğrulayıcı ayrımı'],
    neden: 'Aynı aileden hakem kendi ailesini kayırır (self-preference).',
  },
  {
    id: 'R14', asama: 'RED', faz: 0, baslik: 'RED kanıtı gerçek olmalı',
    olay: 'Test yazıldı ve koşuldu',
    kosul: 'Test beklenen nedenle (doğrulama hatası) kırmızı değil: içe aktarma, sözdizimi ya da altyapı hatası',
    eylem: 'BLOCKED_TEST; test raporu (JUnit) okunur, kodlama başlamaz',
    onler: ['AK-01', 'KP-04', 'B2-S01', 'DK-04'], kaynak: ['Pano B: RED kanıtı olmadan kodlama yok', 'AK-01', 'Pano bulguları: ana akışta RED kapısı yok'],
    neden: 'Sıfır dışı her çıkışı RED saymak, davranışı sınamayan testi "kanıt" yapar.',
  },
  {
    id: 'R15', asama: 'RED', faz: 0, baslik: 'Test kilidi',
    olay: 'RED onaylandı',
    kosul: 'Her zaman',
    eylem: 'Test dosyaları ve test yapılandırması içerik özetiyle kilitlenir; kodlayıcı testi silemez, atlayamaz, zayıflatamaz. Son içerik kontrolü bütün komutlardan sonra yapılır',
    onler: ['AK-02', 'AK-03', 'AK-34', 'DP-09', 'B2-S01'], kaynak: ['Pano B', 'AK-02', 'AK-03', 'Codex DP-09'],
    neden: 'Ajan ölçütü karşılamayı öğrenir: testi değiştirir, siler ya da beklenen değeri sabitler.',
  },
  {
    id: 'R16', asama: 'GRN', faz: 0, baslik: 'Davranış başına deneme',
    olay: 'Kapılar kırmızı döndü',
    kosul: 'Birincil ajan denemesi ≥ {birincil}',
    eylem: 'Bağımsız teşhis; sonra farklı sağlayıcıdan yedek ajan en fazla {yedek} deneme',
    kontroller: [
      { tur: 'sayi', id: 'birincil', etiket: 'Birincil deneme', min: 1, max: 6, varsayilan: 3 },
      { tur: 'sayi', id: 'yedek', etiket: 'Yedek deneme', min: 0, max: 4, varsayilan: 2 }],
    onler: ['B2-S03', 'KP-07'], kaynak: ['policy.yaml per_behavior 3 + 2', 'STARK panosu'],
    neden: 'Aynı ajan aynı hatayı tekrarlar; farklı sağlayıcı farklı kör noktadır.',
  },
  {
    id: 'R17', asama: 'GRN', faz: 0, baslik: 'Görev toplam bütçesi (sert)',
    olay: 'Her deneme ve her model çağrısı',
    kosul: 'Başarısız deneme ≥ {deneme} ya da aktif süre ≥ {dakika} dk ya da maliyet ≥ {tavan} $',
    eylem: 'ERROR; otomatik iş durur, kanıt paketi hazırlanır. Sayaç yeni model, alt ajan ya da yeni koşuyla sıfırlanmaz',
    kontroller: [
      { tur: 'sayi', id: 'deneme', etiket: 'Başarısız deneme', min: 3, max: 30, varsayilan: 10 },
      { tur: 'sayi', id: 'dakika', etiket: 'Aktif süre (insan beklemesi hariç)', birim: 'dk', min: 30, max: 480, adim: 10, varsayilan: 120 },
      { tur: 'sayi', id: 'tavan', etiket: 'Görev maliyet tavanı', birim: '$', min: 5, max: 200, varsayilan: 25 }],
    onler: ['KP-07', 'AK-44', 'AK-50', 'B2-S07', 'D2-02'], kaynak: ['policy.yaml per_task', 'KP-07: sınırlar uyarıya dönüştü (46 ERROR, 47 yeniden başlatma)'],
    neden: 'Yumuşak sınır, yakınsamadan büyüyen harcama demektir.',
  },
  {
    id: 'R18', asama: 'GRN', faz: 1, baslik: 'İlerleme ≠ canlılık',
    olay: '{dakika} dk boyunca yeni commit, test sonucu ya da dosya değişikliği yok',
    kosul: 'Uzun test ya da kurulum koşmuyor (ayrı telemetri)',
    eylem: 'Tıkanıklık çözücü: strateji değiştir, işi böl ya da doğru kişiye soru sor',
    kontroller: [{ tur: 'sayi', id: 'dakika', etiket: 'İlerlemesiz süre', birim: 'dk', min: 5, max: 60, varsayilan: 20 }],
    onler: ['KP-11', 'B2-S03', 'D2-D02', 'D2-D06'], kaynak: ['KP-11: uzun test 3 kez öldürüldü', 'E4: canlılık ilerleme değildir', 'D2 dikişi: heartbeat durdu, ajan 326 araç çağrısına devam etti'],
    neden: 'Süreç çalışıyor diye iş ilerliyor sayılmaz; test koşuyor diye ajan takıldı da sayılmaz.',
  },
  {
    id: 'R19', asama: 'GRN', faz: 0, baslik: 'Heartbeat ve iptal yayılımı',
    olay: 'Uzun ajan adımı sürüyor',
    kosul: '{hb} dk içinde heartbeat yok ya da iş iptal edildi',
    eylem: 'Adım zaman aşımına düşer; sandbox konteyneri öldürülür; sahipsiz konteynerler etiketle temizlenir',
    kontroller: [{ tur: 'sayi', id: 'hb', etiket: 'Heartbeat aralığı', birim: 'dk', min: 1, max: 10, varsayilan: 2 }],
    onler: ['D1-01', 'D1-03', 'AK-18', 'D2-D05', 'D2-06', 'D2-D03', 'AK-26'], kaynak: ['D1', 'AK-18', 'Pano: konteyner iptalde öldürülmeli'],
    neden: 'Heartbeat\'siz uzun adım zombi kalır; iptal edilen iş arkada çalışmayı sürdürür.',
  },
  {
    id: 'R20', asama: 'GRN', faz: 2, baslik: 'Devir paketiyle devam',
    olay: 'Onarım ya da yeniden deneme başlıyor',
    kosul: 'Her zaman',
    eylem: 'Ajan önceki denemenin devir paketini alır (ne denendi, neden kaldı, kanıt); destekleyen çalıştırıcıda oturum sürdürülür',
    onler: ['KP-09', 'D2-06'], kaynak: ['KP-09', 'C2: kayıttaki 35 ajandan 12\'si oturum sürdürmeyi destekliyor'],
    neden: 'Bağlam taşınmayınca aynı iş yeniden keşfedilir ve token maliyeti katlanır.',
  },
  // ---------------- GitHub CI/CD ----------------
  {
    id: 'R21', asama: 'KAP', faz: 0, baslik: 'Zorunlu kapı seti',
    olay: 'PR açıldı ya da güncellendi',
    kosul: 'Her zaman',
    eylem: 'CI aynı SHA üzerinde şu kapıları koşar: {kapilar}',
    kontroller: [{ tur: 'kutu', id: 'kapilar', etiket: 'Kapılar', varsayilan: ['build', 'lint', 'tip', 'unit', 'entegrasyon', 'sast', 'bagimlilik'], secenekler: [
      { deger: 'build', etiket: 'build' }, { deger: 'lint', etiket: 'lint' }, { deger: 'tip', etiket: 'tip denetimi' },
      { deger: 'unit', etiket: 'birim test' }, { deger: 'entegrasyon', etiket: 'entegrasyon testi' }, { deger: 'e2e', etiket: 'uçtan uca test' },
      { deger: 'sast', etiket: 'SAST (Semgrep/CodeQL)' }, { deger: 'bagimlilik', etiket: 'bağımlılık + sır (OSV/gitleaks)' },
      { deger: 'a11y', etiket: 'erişilebilirlik' }, { deger: 'perf', etiket: 'performans' }] }],
    onler: ['B2-S12', 'D2-04'], kaynak: ['Pano G: "burada yapay zekâ yok, makineler kontrol eder"'],
    neden: 'Ucuz ve kesin eleme, pahalı ajan denetiminden önce gelir.',
  },
  {
    id: 'R22', asama: 'KAP', faz: 0, baslik: 'Sahte yeşil yasak',
    olay: 'Kapı sonucu geldi',
    kosul: 'Kararsız (flaky), atlanmış (skip), boş test takımı ya da atlatma (bypass) var',
    eylem: 'Başarı sayılmaz; kapı kalır',
    onler: ['B2-S10', 'D2-01', 'D2-D10', 'KP-14'], kaynak: ['policy.yaml gates', 'D2: yanlış başarı sinyali'],
    neden: 'Ajan kararsız testi atlar ya da daraltır; CI geçer ama davranış doğrulanmamıştır.',
  },
  {
    id: 'R23', asama: 'KAP', faz: 0, baslik: 'Gerekli kontroller bitmeden karar yok',
    olay: 'CI durumu değişti',
    kosul: 'Zorunlu kontrol listesinin tamamı bitmedi',
    eylem: 'Beklenir; erken "başarılı" yok',
    onler: ['AK-62', 'D2-04', 'AK-61'], kaynak: ['AK-62'],
    neden: 'İlk biten kontrolün yeşili, bütün kapının yeşili değildir.',
  },
  {
    id: 'R24', asama: 'KAP', faz: 1, baslik: 'Son aday yeniden doğrulanır',
    olay: 'CI onarımı, çatışma çözümü ya da test komutu kodu değiştirdi',
    kosul: 'Yeni SHA oluştu',
    eylem: 'İnceleme, oracle ve güvenlik kanıtı yeni SHA için yeniden istenir; eski yeşil taşınmaz',
    onler: ['DP-03', 'DP-09', 'DK-07'], kaynak: ['Codex DP-03', 'Pano E: eski yeşil sonuç yeni SHA\'ya taşınmaz'],
    neden: 'İnceleme A koduna onay verdi; birleşen kod C olabilir.',
  },
  {
    id: 'R25', asama: 'KAP', faz: 0, baslik: 'Tarayıcı hata kodu gizlenemez',
    olay: 'Sır ya da güvenlik taraması koştu',
    kosul: 'Araç yok, işlem hatası ya da bulgu var',
    eylem: 'Her biri ayrı sonuçtur; hiçbiri başarıya çevrilemez ("|| echo" yasak)',
    onler: ['DP-01', 'B2-S06'], kaynak: ['Codex DP-01'],
    neden: 'Bulguyu yakalayan tarayıcının çıkış kodu kabuk ifadesiyle başarıya dönüşebiliyor.',
  },
  {
    id: 'R26', asama: 'QA', faz: 1, baslik: 'Farklı sağlayıcıdan bağımsız QA',
    olay: 'Kapılar yeşil',
    kosul: 'Her zaman',
    eylem: 'QA ajanı senaryoları kabul ölçütlerinden çıkarır; kodlayıcının "geçti" beyanı kanıt sayılmaz; en fazla {tur} düzeltme turu',
    kontroller: [{ tur: 'sayi', id: 'tur', etiket: 'Düzeltme turu', min: 1, max: 4, varsayilan: 2 }],
    onler: ['B2-S01', 'B2-S14', 'AK-05', 'D2-07'], kaynak: ['Pano C', 'A3: model dış geri bildirim olmadan kendini düzeltemez'],
    neden: 'Ajan 54 döngünün her birinde iyileşme iddia etti; %56\'sında değişim sıfır ya da negatifti (A3).',
  },
  {
    id: 'R27', asama: 'QA', faz: 2, baslik: 'Mutasyon testi',
    olay: 'QA başladı',
    kosul: 'Risk ≥ orta ve değişen modül var',
    eylem: 'Değişen modüllerde mutasyon testi; skor < %{esik} ise QA bulgusu',
    kontroller: [{ tur: 'sayi', id: 'esik', etiket: 'Mutasyon skoru eşiği', birim: '%', min: 30, max: 90, varsayilan: 60 }],
    onler: ['AK-04', 'B2-S01', 'KP-04'], kaynak: ['Pano bulguları: %100 AC→test eşlemesi test gücünü ölçmez', 'C5'],
    neden: 'Testin var olması, yanlış kodu yakaladığını göstermez.',
  },
  {
    id: 'R28', asama: 'QA', faz: 1, baslik: 'Kabul eşlemesi tam ve tekil',
    olay: 'QA raporu hazır',
    kosul: 'Bir ölçüt iki kez eşlenmiş ya da eşlenmemiş ölçüt var',
    eylem: 'Kapı kalır; eksik ölçüt için test, gerekçeli kapsam kararı ya da açık başarısızlık',
    onler: ['DP-08', 'AK-07', 'DK-01'], kaynak: ['Codex DP-08', 'AK-07'],
    neden: 'Yalnız satır sayısına bakan kapı, aynı ölçütün iki kez eşlenmesini geçirir.',
  },
  {
    id: 'R29', asama: 'RSK', faz: 1, baslik: 'Risk hesaplanır, beyan edilmez',
    olay: 'Değişiklik birleştirmeye hazır',
    kosul: 'Her zaman',
    eylem: 'Risk = en yüksek(beyan, hassas yol kuralı, fark büyüklüğü). Hassas yollar: {yollar}. Yasaklı → geri al + insana; yüksek → insan onayı; orta/düşük → otomatik',
    kontroller: [{ tur: 'kutu', id: 'yollar', etiket: 'Hassas yollar', varsayilan: ['auth', 'odeme', 'goc', 'altyapi', 'kisisel'], secenekler: [
      { deger: 'auth', etiket: 'kimlik ve yetki' }, { deger: 'odeme', etiket: 'ödeme / bordro' }, { deger: 'goc', etiket: 'veritabanı göçü' },
      { deger: 'altyapi', etiket: 'altyapı ve CI' }, { deger: 'kisisel', etiket: 'kişisel veri' }] }],
    onler: ['AK-40', 'KP-04'], kaynak: ['policy.yaml risk', 'Pano bulguları: yasaklı risk otomatik döngüye dönüyordu', 'AK-40'],
    neden: '"Düşük" beyanı plan onayını ve insan birleştirmesini atlatabiliyor.',
  },
  {
    id: 'R30', asama: 'RSK', faz: 2, baslik: 'Yetki kararları motorda',
    olay: 'İş yetkilendirme mantığına dokunuyor',
    kosul: 'Her zaman',
    eylem: 'Karar kural motorunda (ör. OpenFGA); ajan yalnız modeli ve testlerini yazar',
    onler: ['B2-S04'], kaynak: ['Pano: authorization.agent → OpenFGA'],
    neden: 'Yetki kararı yorum değil, deterministik bir karardır.',
  },
  {
    id: 'R31', asama: 'MQ', faz: 0, baslik: 'Birleştirme kuyruğu',
    olay: 'PR onaylandı',
    kosul: 'Her zaman',
    eylem: 'PR kuyruğa girer; güncel ana dalla birleşik sonuç CI\'dan geçmeden birleşmez; yönetici atlatması kapalı',
    onler: ['AK-28', 'B2-S09', 'D2-04', 'KP-16'], kaynak: ['AK-28', 'C6: tek trunk entegrasyon kapasitesi'],
    neden: 'Her biri tek başına doğru iki değişiklik birlikte ana dalı kırabilir.',
  },
  {
    id: 'R32', asama: 'MQ', faz: 0, baslik: 'Yazar kimliği korunur',
    olay: 'Birleştirme yapılıyor',
    kosul: 'Her zaman',
    eylem: 'Karar ekranındaki yöntemle birleştirilir; yazar ve committer korunur, yapay zekâ ortak yazar satırı eklenmez',
    onler: ['AK-42', 'D2-03'], kaynak: ['AK-42', 'Kişisel git politikası'],
    neden: 'GitHub\'ın squash ya da merge commit\'inde committer "GitHub" olur.',
  },
  {
    id: 'R33', asama: 'MQ', faz: 1, baslik: 'Kırık trunk\'ta dondurma',
    olay: 'Ana dal CI\'ı kırmızı ya da alpha sağlıksız',
    kosul: 'Her zaman',
    eylem: 'Projeye yeni birleştirme durur; yalnız onarım ve geri alma yolu açık kalır (ayrı önkoşullarla)',
    onler: ['AK-31', 'DP-02'], kaynak: ['AK-31', 'Codex DP-02'],
    neden: 'Sağlıklı alpha şartı, alpha\'yı düzeltecek geri almayı da kilitleyebiliyor.',
  },
  {
    id: 'R34', asama: 'MQ', faz: 2, baslik: 'Göç kapısı',
    olay: 'Değişiklik veritabanı göçü içeriyor',
    kosul: 'Her zaman',
    eylem: 'Tek göç başı; göç ve geri alma testi temiz veritabanında koşar',
    onler: ['AK-32'], kaynak: ['AK-32'],
    neden: 'Git çakışması olmadan iki göç ana dalı ve alpha veritabanını bozabilir.',
  },
  // ---------------- alpha.example.com ----------------
  {
    id: 'R35', asama: 'DEP', faz: 0, baslik: 'Sürüm kimliği doğrulaması',
    olay: 'alpha dağıtımı bitti',
    kosul: '/_surum birleşim SHA\'sını içeriyor, /_saglik 200 ve duman testi geçti',
    eylem: 'İş Human Test\'e taşınır; değilse dağıtım hatası (kod hatası değil)',
    onler: ['AK-29', 'D2-01', 'KP-14'], kaynak: ['AK-29', 'Codex ACCEPTANCE: aynı artefakt + alpha duman testi'],
    neden: 'İnsan, test ettiği sürümün birleşen kod olduğundan emin olmalı.',
  },
  {
    id: 'R36', asama: 'DEP', faz: 1, baslik: 'Dağıtım sırası korunur',
    olay: 'Geç biten eski bir CI işi alpha\'ya dağıtmak istiyor',
    kosul: 'Ortamdaki hedef nesil daha yeni',
    eylem: 'Dağıtım reddedilir; bilinçli geri alma ayrı yetkili yayın nesli ister',
    onler: ['DP-10', 'AK-30'], kaynak: ['Codex DP-10'],
    neden: 'Yavaş eski CI, hızlı yeni sürümden sonra alpha\'yı geri taşıyabilir.',
  },
  {
    id: 'R37', asama: 'DEP', faz: 1, baslik: 'Belirsiz dış etki (unknown_effect)',
    olay: 'Push, PR ya da dağıtım çağrısı zaman aşımına uğradı',
    kosul: 'Sonuç bilinmiyor',
    eylem: 'Körlemesine tekrar yok; önce GitHub/dağıtım durumu sorgulanır, etki defterine yazılır, sonra karar verilir',
    onler: ['D1-04', 'DP-12', 'D2-D04'], kaynak: ['Codex: etki defteri ve unknown_effect', 'E4'],
    neden: 'Zaman aşımı işlemin olmadığı anlamına gelmez; tekrar çift commit ya da çift maliyet üretir.',
  },
  {
    id: 'R38', asama: 'DEP', faz: 1, baslik: 'Ortam eşliği',
    olay: 'Kod bir ortama çıkıyor',
    kosul: 'Her zaman',
    eylem: 'Sandbox, CI ve alpha aynı imaj ve kilit dosyasından; CI\'da üretilen imaj ortamlar boyunca aynen terfi eder',
    onler: ['B2-S15', 'DK-02'], kaynak: ['B2 S15', 'A0: tek imajla alpha → beta → rc → prod'],
    neden: '"Bende çalışıyor": sandbox, CI ve alpha farklıysa sonuç taşınmaz.',
  },
  {
    id: 'R39', asama: 'HT', faz: 0, baslik: 'İnsan beklemesi sahipli ve süreli',
    olay: 'İş insan eylemi bekliyor (PO, QA, Human Test)',
    kosul: '{hatirlat} saat geçti → hatırlat; {yukselt} saat geçti → yükselt',
    eylem: 'Sorumluya hatırlatma, ardından team lead/RTE\'ye yükseltme. Sessiz zaman aşımı yok',
    kontroller: [
      { tur: 'sayi', id: 'hatirlat', etiket: 'Hatırlatma', birim: 'saat', min: 4, max: 72, varsayilan: 24 },
      { tur: 'sayi', id: 'yukselt', etiket: 'Yükseltme', birim: 'saat', min: 8, max: 168, varsayilan: 48 }],
    onler: ['KP-15', 'KP-13', 'AK-52', 'AK-53', 'AK-54', 'D1-03', 'B2-S13'], kaynak: ['KP-15: kabul 7 gün bekledi, P7D ile KESTRA_FAILED', 'E6'],
    neden: 'Önceki pilotta ürün birleşmiş ve yeşilken kabul hiç başlamadı; iş 7 gün sonra sessizce düştü.',
  },
  {
    id: 'R40', asama: 'HT', faz: 0, baslik: 'Test paketi formdan türetilir',
    olay: 'İş Human Test\'e geldi',
    kosul: 'Her zaman',
    eylem: 'Paket = formdaki kabul ölçütleri birebir + {testler}',
    kontroller: [{ tur: 'kutu', id: 'testler', etiket: 'İnsan testleri', varsayilan: ['yolculuk', 'negatif', 'monkey', 'db', 'baska'], secenekler: [
      { deger: 'yolculuk', etiket: 'kullanıcı yolculuğu' }, { deger: 'negatif', etiket: 'olumsuz senaryo' },
      { deger: 'monkey', etiket: 'rastgele etkileşim (seed + eylem kaydı)' }, { deger: 'db', etiket: 'veritabanına yansıma' }, { deger: 'baska', etiket: '"başka?" serbest gözlem' }] }],
    onler: ['AK-08', 'KP-04', 'AK-33'], kaynak: ['İlk kapı panosu (S-096)', 'AK-08', 'Codex ACCEPTANCE'],
    neden: 'Planlayıcının çıktısından türetilen paket, insanın istediğini değil ajanın anladığını test eder.',
  },
  {
    id: 'R41', asama: 'HT', faz: 1, baslik: 'Kanıtsız onay yok',
    olay: 'Test eden Done istedi',
    kosul: 'Her madde için ✓/✗ ve not yok',
    eylem: 'Done\'a geçiş reddedilir; eksik maddeler gösterilir',
    onler: ['AK-09', 'B2-S13'], kaynak: ['AK-09'],
    neden: 'Yorgun onaycı otomatik onaya kayar; kanıt şablonu bunu görünür kılar.',
  },
  {
    id: 'R42', asama: 'HT', faz: 1, baslik: 'Human Test WIP sınırı',
    olay: 'Yeni görev başlamak istiyor',
    kosul: 'Ekipte bekleyen Human Test ≥ {wip}',
    eylem: 'Yeni görev başlamaz, hazırlıkta bekler (geri basınç)',
    kontroller: [{ tur: 'sayi', id: 'wip', etiket: 'Bekleyen Human Test sınırı', min: 1, max: 20, varsayilan: 4 }],
    onler: ['AK-52', 'B2-S13'], kaynak: ['AK-52', 'C6: ölçeği inceleme kapasitesi belirler'],
    neden: 'Ajan üretimi arttıkça darboğaz insan testine kayar.',
  },
  {
    id: 'R43', asama: 'KAB', faz: 0, baslik: 'Ret → geri alma + yeni iş',
    olay: 'İnsan Rejected dedi',
    kosul: 'Her zaman',
    eylem: 'alpha\'dan geri alma PR\'ı (aynı kapılardan); ret notlarıyla yeni iş; bağımlı işler yeniden değerlendirilir',
    onler: ['AK-10', 'DK-03', 'KP-16'], kaynak: ['AK-10', 'Codex DK-03', 'Pano F'],
    neden: 'Reddedilen kod alpha\'da kalırsa sonraki testler kirli sürüm üzerinde yapılır.',
  },
  {
    id: 'R44', asama: 'KAB', faz: 1, baslik: 'İnsan kararı kalıcıdır',
    olay: 'İnsan Rejected ya da iptal yaptı',
    kosul: 'Fabrika aynı anda durum yazıyor',
    eylem: 'İnsan kararı bot zaman damgasıyla elenemez; sonraki yan etkilerin yetkisi değişir',
    onler: ['DP-07', 'AK-43', 'AK-48'], kaynak: ['Codex DP-07', 'AK-43'],
    neden: 'Human Test yazımıyla ret yarışırsa ret "eski" diye düşebiliyor.',
  },
  {
    id: 'R45', asama: 'KAB', faz: 1, baslik: 'Regresyon testi',
    olay: 'alpha\'da ya da sunumda hata bulundu',
    kosul: 'Her zaman',
    eylem: 'Bağlantılı hata kaydı açılır; test ajanı hatalı sürümde kırmızı, düzeltilmişte yeşil olan regresyon testi yazar',
    onler: ['B2-S12'], kaynak: ['Pano F'],
    neden: 'Düzeltilen hata testle kilitlenmezse geri gelir.',
  },
  // ---------------- Her adımda: hata ve toparlanma ----------------
  {
    id: 'R46', asama: 'HATA', faz: 0, baslik: 'Hata sınıfı yapılandırılmış alandan',
    olay: 'Adım hata verdi',
    kosul: 'Her zaman',
    eylem: 'Sınıf, CLI\'nin yapılandırılmış hata alanından okunur (metin eşleme yok); her sınıfın sahibi ve rotası var: ortam, test yazarı, ürün, sağlayıcı, kullanıcı kararı',
    onler: ['KP-12', 'KP-19', 'AK-21'], kaynak: ['KP-12: "CAPACITY" alt dizesi 4.762 CLAIM\'lik döngü üretti', 'KP-19'],
    neden: 'Bağlam taşması "kapasite beklemesi" sanıldı; saatlerce ilerlemesiz döngü oluştu.',
  },
  {
    id: 'R47', asama: 'HATA', faz: 0, baslik: 'Geçici altyapı hatası bütçeden sayılmaz',
    olay: '429, 529 ya da ağ hatası',
    kosul: 'Her zaman',
    eylem: '{tekrar} tekrar, {bekleme} sn\'den başlayan artan aralıkla; bütçeden düşmez. Kalıcıysa BLOCKED_INFRA ve işletime devir',
    kontroller: [
      { tur: 'sayi', id: 'tekrar', etiket: 'Tekrar', min: 0, max: 5, varsayilan: 2 },
      { tur: 'sayi', id: 'bekleme', etiket: 'İlk bekleme', birim: 'sn', min: 5, max: 120, varsayilan: 10 }],
    onler: ['D1-07', 'D2-09', 'B2-S03'], kaynak: ['policy.yaml infra: 2 tekrar, 10/30 sn', 'Hermes Kanban: exit 75 bütçeden sayılmaz'],
    neden: 'Sağlayıcı yoğunluğu ajanın başarısızlığı değildir; sayılırsa iş haksız yere ERROR olur.',
  },
  {
    id: 'R48', asama: 'HATA', faz: 0, baslik: 'Bellek taşması kanıtla',
    olay: 'Süreç öldü (çıkış 137)',
    kosul: 'cgroup oom_kill sayacı arttı',
    eylem: 'Bir üst kaynak profiliyle yeniden koşar ({profil}); tarayıcı testleri {grup}\'lik gruplarla. oom_kill yoksa bellek taşması sayılmaz',
    kontroller: [
      { tur: 'radyo', id: 'profil', etiket: 'Profil merdiveni', varsayilan: '2-4-8', secenekler: [{ deger: '1-2-4', etiket: '1 → 2 → 4 GiB' }, { deger: '2-4-8', etiket: '2 → 4 → 8 GiB' }] },
      { tur: 'sayi', id: 'grup', etiket: 'Tarayıcı testi grup boyu', min: 10, max: 200, adim: 10, varsayilan: 50 }],
    onler: ['KP-10', 'D1-08', 'B2-S02', 'D2-06'], kaynak: ['E6: 1 GiB tarayıcı konteyneri OOM; 2g\'de 3/3 geçti, ~150 testte 2g yetmedi', 'E4: çıkış 137 tek başına OOM değildir'],
    neden: 'Önceki pilotta "rapor yok" sonucu ürün hatası ya da ajan takılması sanıldı; sınır üç kez yeniden tasarlandı.',
  },
  {
    id: 'R49', asama: 'HATA', faz: 0, baslik: 'Sahipsiz bekleme yok',
    olay: 'İş herhangi bir bekleme durumuna girdi',
    kosul: 'Sorumlu, uyanma olayı, son ilerleme ya da son tarih eksik',
    eylem: 'Alarm; bekleme kaydı tamamlanmadan iş beklemeye alınmaz',
    onler: ['KP-13', 'KP-15', 'D1-03', 'DK-05'], kaynak: ['KP-13: dokuz durmanın hepsi kullanıcı sorunca fark edildi', 'E5: bekleyen işin yönlendirilebilir sahibi olmalı'],
    neden: 'Alarm kaydı onarım sayıldı; 13 ve 5 saatlik boş beklemeler oluştu.',
  },
  {
    id: 'R50', asama: 'HATA', faz: 0, baslik: 'Dürüst durum',
    olay: 'Bir adım bitti',
    kosul: 'Her zaman',
    eylem: 'Çağrının bitmesi başarı değildir; teşhis, kurulum, paket ve teslim ayrı durumlardır; bilinmeyen sıfır sayılmaz',
    onler: ['KP-14', 'D2-01', 'D2-07', 'DK-07', 'AK-20', 'DE-06'], kaynak: ['KP-14', 'D2: yanlış başarı sinyali'],
    neden: 'Kullanıcı gerçek ilerlemeyi göremedi ve defalarca "bitti mi?" diye sordu.',
  },
  {
    id: 'R51', asama: 'HATA', faz: 1, baslik: 'Dış gözlemci',
    olay: 'Her {aralik} dakikada',
    kosul: 'RUNNING görünen iş ilerlemiyor ya da iş akışı görevi hata veriyor',
    eylem: 'İş akışı dışındaki gözlemci alarm verir ve işi sahibine yönlendirir',
    kontroller: [{ tur: 'sayi', id: 'aralik', etiket: 'Gözlem aralığı', birim: 'dk', min: 1, max: 30, varsayilan: 5 }],
    onler: ['D1-01', 'D1-11', 'D2-D06'], kaynak: ['E4: iş akışı kodundaki düz istisna işi RUNNING bırakıyor; dış gözlemci 0,4 sn\'de gördü', 'D1'],
    neden: 'Sağlık ucu "200" derken iş ilerlemeyebilir.',
  },
  {
    id: 'R52', asama: 'HATA', faz: 1, baslik: 'İş akışı ve şema sürümleme',
    olay: 'İş akışı kodu ya da veri sözleşmesi değişti',
    kosul: 'Bekleyen koşu var',
    eylem: 'Değişiklik sürümle girer; eski koşular eski sürümle biter; yeniden oynatma ve üretici/tüketici uyum testi CI\'da',
    onler: ['D1-05', 'AK-19', 'KP-17'], kaynak: ['AK-19', 'D1: determinizm ve sürümleme', 'KP-17'],
    neden: 'Canlı onarım bir sonraki kapıyı bozdu; kod değişince bekleyen iş akışları kilitlenebilir.',
  },
  {
    id: 'R53', asama: 'HATA', faz: 1, baslik: 'Büyük çıktı geçmişe girmez',
    olay: 'Ajan transkripti, log ya da büyük çıktı üretildi',
    kosul: 'Her zaman',
    eylem: 'Dosya deposunda tutulur, iş akışında yalnız referans; uzun döngülerde geçmiş yenilenir (continue-as-new)',
    onler: ['D1-06', 'AK-27'], kaynak: ['D1: geçmiş ve yük boyutu', 'AK-27'],
    neden: 'LLM çıktıları motorun durumuna yazılınca geçmiş sınırı aşılır.',
  },
  {
    id: 'R54', asama: 'HATA', faz: 0, baslik: 'Tek durum sahibi',
    olay: 'Görevde herhangi bir durum değişikliği',
    kosul: 'Her zaman',
    eylem: 'Görev durumunu yalnız durum sahibi yazar; Plane durumu yansıtır; ikinci araç yalnız tetik ya da bildirim yapar',
    onler: ['D1-13', 'KP-01', 'KP-08', 'D2-06'], kaynak: ['Pano: tek durum sahibi', 'E6: Kestra yokladı, Python işi yaptı ("iki beyin")', 'E4: her durum alanının tek yazıcısı'],
    neden: 'İki sistem aynı durumu tutarsa "bölünmüş beyin" oluşur; pilotun ana kök nedeni buydu.',
  },
  {
    id: 'R55', asama: 'HATA', faz: 0, baslik: 'Açılış doğrulaması',
    olay: 'Servis başlıyor',
    kosul: 'Yapılandırma, kimlik, ağ, imaj, sorumlular ya da Plane durumları eksik veya geçersiz',
    eylem: 'Servis açık bir mesajla başlamaz',
    onler: ['KP-20', 'AK-37', 'AK-46', 'AK-54', 'D2-D11'], kaynak: ['KP-20: Caddy sözdizimi ve eklenti dizini izni', 'AK-54'],
    neden: 'Ajanlar çalışmadan erişim ve akış motoru durabildi.',
  },
  {
    id: 'R56', asama: 'HATA', faz: 0, baslik: 'Canlı yama yok',
    olay: 'Fabrika kodu, politika ya da skill değişecek',
    kosul: 'Her zaman',
    eylem: 'Değişiklik yalnız PR + test + sürümle girer; canlı sistemde elle düzeltme yapılmaz',
    onler: ['KP-02', 'KP-17'], kaynak: ['KP-02', 'KP-17', 'A3: talimat değişikliği kod gibi'],
    neden: 'Önceki pilotta düzeltmeleri fabrika değil GUI oturumları yaptı; geri alma ve tekrar üretim kalmadı.',
  },
  // ---------------- Her adımda: bütçe ve kapasite ----------------
  {
    id: 'R57', asama: 'BUT', faz: 0, baslik: 'Eşzamanlılık formülü',
    olay: 'Yeni görev başlayacak',
    kosul: 'Eşzamanlı iş ≥ en küçük(insan inceleme kapasitesi, kuyruk kapasitesi, bütçe) ya da kişi başına {wip} aktif iş aşıldı',
    eylem: 'Görev sıraya girer',
    kontroller: [{ tur: 'sayi', id: 'wip', etiket: 'Kişi başına aktif iş', min: 1, max: 3, varsayilan: 1 }],
    onler: ['KP-08', 'DP-11', 'B2-S13', 'AK-16', 'AK-17'], kaynak: ['C6 §1', 'STARK: kişi başına 1 aktif iş'],
    neden: 'Eşzamanlılık artışı önceki pilotta verime dönüşmedi.',
  },
  {
    id: 'R58', asama: 'BUT', faz: 0, baslik: 'Sağlayıcı tavanı devre kesici',
    olay: 'Harcama tavanı, 402 ya da kimlik hatası görüldü',
    kosul: 'Her zaman',
    eylem: 'Fabrika geneli "duraklat"; yeni ajan çağrısı yapılmaz; insana tek alarm gider',
    onler: ['AK-22', 'KP-05', 'D2-02', 'D2-D09'], kaynak: ['C6: tavanda istekler ay sonuna kadar 429', 'D2 dikişi: kalıcı 402\'de 3 tekrar oturum sayısını katladı'],
    neden: 'Tavan dolunca bütün görevler aynı anda hataya düşer.',
  },
  {
    id: 'R59', asama: 'BUT', faz: 1, baslik: 'Çağrı öncesi bütçe rezervasyonu',
    olay: 'Model çağrısı yapılacak',
    kosul: 'Kalan bütçe tahmini maliyetten az',
    eylem: 'Çağrı yapılmaz; yarıda kalan ve tekrar edilen çağrılar da sayılır',
    onler: ['AK-49', 'AK-50', 'D2-02'], kaynak: ['E4: çağrı öncesi rezervasyon', 'AK-49'],
    neden: 'Bütçe çağrıdan sonra denetlenirse tavan her zaman aşılır.',
  },
  {
    id: 'R60', asama: 'BUT', faz: 2, baslik: 'Kapasite rol ve rota bazında',
    olay: 'Kapasite kararı veriliyor',
    kosul: 'Her zaman',
    eylem: 'Kapasite, işi yürütecek rolden ve kilit alınmadan önce ölçülür; tek inceleyici bütün kuyruğu kilitleyemez',
    onler: ['KP-18', 'KP-05'], kaynak: ['KP-18'],
    neden: 'Kodlayıcı kapasitesi varken üretim durdu; RAM eklemek bunu çözmez.',
  },
  {
    id: 'R61', asama: 'BUT', faz: 0, baslik: 'Politika anlık görüntüsü',
    olay: 'Koşu başladı',
    kosul: 'Her zaman',
    eylem: 'policy.yaml sürümü koşu başında sabitlenir; bütün adımlar aynı özeti kullanır; canlı ayar koşuya girmez',
    onler: ['DP-04', 'AK-47'], kaynak: ['policy.yaml: run başında sabitlenir', 'Codex DP-04'],
    neden: 'Aynı koşuda iki farklı kural sürümü, açıklanamayan sonuç üretir.',
  },
  {
    id: 'R62', asama: 'BUT', faz: 1, baslik: 'Kaynak kotaları',
    olay: 'Sandbox, log ya da çalışma alanı büyüyor',
    kosul: 'Disk kotası, log boyutu ya da saklama süresi aşıldı',
    eylem: 'Kota uygulanır; loglar döndürülür; bekleyen çalışma alanı arşivlenip temizlenir',
    onler: ['AK-11', 'AK-12', 'AK-13', 'AK-14', 'B2-S02'], kaynak: ['AK-11 … AK-14'],
    neden: 'Tek görev host diskini doldurup veritabanını ve orkestratörü düşürebilir.',
  },
  // ---------------- Her adımda: güvenlik ----------------
  {
    id: 'R63', asama: 'GUV', faz: 0, baslik: 'Çıkış izin listesi',
    olay: 'Sandbox dışarıya bağlanmak istiyor',
    kosul: 'Hedef izin listesinde değil (izinli: {izinli})',
    eylem: 'Bağlantı reddedilir ve kaydedilir',
    kontroller: [{ tur: 'kutu', id: 'izinli', etiket: 'İzinli hedefler', varsayilan: ['model', 'paket'], secenekler: [
      { deger: 'model', etiket: 'model API\'si' }, { deger: 'paket', etiket: 'yerel paket vekili' },
      { deger: 'dok', etiket: 'doküman sunucusu' }, { deger: 'github', etiket: 'GitHub (yalnız işçi)' }] }],
    onler: ['AK-36', 'B2-S05', 'B2-S06'], kaynak: ['AK-36', 'Çıkış vekili Colima\'da doğrulandı (27.09): example.com ve gist 403'],
    neden: 'Bağımlılık ya da istem enjeksiyonu, açık ağda anahtarı dışarı taşır.',
  },
  {
    id: 'R64', asama: 'GUV', faz: 0, baslik: 'Sırlar sandbox\'a girmez',
    olay: 'Ajan çalışma alanı hazırlanıyor',
    kosul: 'Her zaman',
    eylem: 'Jeton URL\'ye ya da diske yazılmaz; kodlayıcı üretim sırrı, Docker soketi ya da genel SSH almaz; dışa yazma dar yetkili deterministik ağ geçidiyle',
    onler: ['AK-35', 'AK-38', 'B2-S06', 'D2-05', 'AK-41', 'AK-58'], kaynak: ['AK-35', 'Codex AGENTS.md yönergesi'],
    neden: 'Ajan .env dosyalarını okur, sırları loglara ve commit\'lere taşır.',
  },
  {
    id: 'R65', asama: 'GUV', faz: 0, baslik: 'Yıkıcı işlem teknik olarak engelli',
    olay: 'Ajan silme, zorla push ya da ortam silme komutu çalıştırmak istiyor',
    kosul: 'Her zaman',
    eylem: 'İzin ve hook düzeyinde engellenir; .md içindeki yasak tek başına yeterli sayılmaz',
    onler: ['B2-S04'], kaynak: ['B2 S04', 'A3: deterministik kontrol > izin/hook > skill > .md'],
    neden: 'Doğal dildeki "dokunma" yasağı teknik bir kontrol değildir.',
  },
  {
    id: 'R66', asama: 'GUV', faz: 1, baslik: 'Skill ve MCP yalnız iç katalogdan',
    olay: 'Ajan skill ya da MCP sunucusu yükleyecek',
    kosul: 'Paket iç katalogda sabit sürüm ve özetle onaylı değil',
    eylem: 'Yüklenmez; pazardan doğrudan kurulum yok; özet değişirse yeniden onay',
    onler: ['DE-07', 'DK-08', 'B2-S05', 'D2-05'], kaynak: ['A3: ClawHub\'daki 2.857 skill\'den 341\'i zararlıydı', 'Codex REGISTRY-POLICY'],
    neden: 'Pazar keşif kaynağıdır, güven kaynağı değil.',
  },
  {
    id: 'R67', asama: 'GUV', faz: 1, baslik: 'KVKK',
    olay: 'Görev kişisel veri içeriyor',
    kosul: 'Her zaman',
    eylem: 'Log ve istemde maskeleme; yurt dışı aktarım dayanağı ve saklama süresi belgelenir',
    onler: ['B2-S16', 'AK-55'], kaynak: ['B2 S16', 'AK-55'],
    neden: 'İstemler ve izler yurt dışındaki sağlayıcıya gidiyorsa KVKK aktarım rejimi uygulanır.',
  },
  // ---------------- Her adımda: gözlem ve öğrenme ----------------
  {
    id: 'R68', asama: 'GOZ', faz: 1, baslik: 'Görev başına maliyet ve iz',
    olay: 'Her adım',
    kosul: 'Her zaman',
    eylem: 'OpenTelemetry → Langfuse: görev başına token, maliyet, süre; ajan ve insan kaynaklı değişiklik ayrı etiketlenir',
    onler: ['B2-S07', 'D2-02', 'KP-05', 'AK-51'], kaynak: ['Pano yol haritası Faz 1', 'A3 metrikleri'],
    neden: 'Ajan-saat maliyeti 5–9 kat belirsiz; ölçülmeden ölçek açılamaz (C6).',
  },
  {
    id: 'R69', asama: 'GOZ', faz: 1, baslik: 'Yedek ve geri yükleme tatbikatı',
    olay: 'Her gün / her ay',
    kosul: 'Her zaman',
    eylem: 'Veritabanı ve iş akışı kalıcılığı günlük yedeklenir; ayda bir geri yükleme tatbikatı; uyarılar kurulu',
    onler: ['AK-56', 'AK-57', 'D1-09', 'AK-59'], kaynak: ['AK-56', 'AK-57'],
    neden: 'Yeşil görünen yedek geri yüklenemeyebilir (risk senaryosu SS-119).',
  },
  {
    id: 'R70', asama: 'OGR', faz: 2, baslik: 'Yönerge ve skill değişikliği eval\'den geçer',
    olay: 'Yeni ya da değişen skill veya AGENTS.md önerisi (Hermes önerileri dahil)',
    kosul: 'Her zaman',
    eylem: 'PR → sabit örnek kümesinde karşılaştırma (Promptfoo/Inspect) → insan onayı → birleştirme',
    onler: ['DE-07', 'B2-S14'], kaynak: ['Pano L', 'Hermes değerlendirmesi: öneri → eval → onay', 'A3: modelin kendi ürettiği skill\'ler ortalamada fayda sağlamadı'],
    neden: 'Her hatada .md\'ye satır eklemek başarıyı düşürüp maliyeti artırabilir.',
  },
  {
    id: 'R71', asama: 'OGR', faz: 0, baslik: 'Kuralları kademeli aç',
    olay: 'Yeni kural, ekip ya da katman eklenmek isteniyor',
    kosul: 'Önceki fazın kapı metrikleri ölçülmedi',
    eylem: 'Eklenmez; önce ölçüm (kabul oranı, CI turu, kuyruk süresi, kabul edilen değişiklik başına maliyet)',
    onler: ['KP-03', 'AK-60'], kaynak: ['KP-03: 7 günde SAFe, ECA, Kaizen eklendi; temel akış sağlamlaşmadı', 'C6 §6'],
    neden: 'Önceki pilotta ECA kuralları da temel akış kanıtlanmadan eklendi.',
  },
  {
    id: 'R72', asama: 'OGR', faz: 2, baslik: 'Sürüm sabitleme ve çıkış planı',
    olay: 'Araç, model ya da protokol sürümü değişiyor',
    kosul: 'Her zaman',
    eylem: 'Sürümler sabitlenir; değişim önce altın görevlerde iki sürümle koşulur; kritik her araç için çıkış planı ve tatbikat',
    onler: ['D1-10', 'D1-12', 'D2-08', 'B2-S08', 'D2-D08', 'D2-D01'], kaynak: ['C3: dikiş haritası ve değişim testleri'],
    neden: 'Ajan çalıştırıcıları ve modeller en oynak katmanlardır; 12–13 ayda değişir (C3).',
  },
];

export const kuralBul = (id: string) => KURALLAR.find((k) => k.id === id);
